# Generated by Django 3.2.8 on 2021-10-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(blank=True, max_length=32)),
                ('title', models.CharField(max_length=32)),
                ('message', models.TextField()),
                ('uploaded', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
