# Generated by Django 3.2.7 on 2021-10-25 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bed_capacity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rumahsakit',
            name='kode_lokasi',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
    ]
