# Generated by Django 3.2.7 on 2021-10-25 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bed_capacity', '0002_rumahsakit_kode_lokasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='rumahsakit',
            name='telp',
            field=models.CharField(default='08', max_length=25),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BedRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=40)),
                ('alamat', models.CharField(max_length=60)),
                ('gender', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('umur', models.IntegerField()),
                ('telp', models.CharField(max_length=15)),
                ('rs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bed_capacity.rumahsakit')),
            ],
        ),
    ]
