# Generated by Django 3.2.7 on 2021-10-25 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bed_capacity', '0003_auto_20211025_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedrequest',
            name='rs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bed_capacity.rumahsakit'),
        ),
    ]
