# Generated by Django 3.2.7 on 2021-10-27 03:44

import bed_capacity.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bed_capacity', '0005_alter_bedrequest_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedrequest',
            name='telp',
            field=models.CharField(max_length=15, validators=[bed_capacity.models.validate_telp]),
        ),
        migrations.AlterField(
            model_name='rumahsakit',
            name='telp',
            field=models.CharField(max_length=25, validators=[bed_capacity.models.validate_telp]),
        ),
    ]
