# Generated by Django 3.2.7 on 2021-10-28 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bed_capacity', '0006_auto_20211027_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wilayah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='rumahsakit',
            name='kode_lokasi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bed_capacity.wilayah'),
        ),
    ]
