# Generated by Django 3.2.7 on 2021-10-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bed_capacity', '0010_alter_rumahsakit_kode_lokasi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rumahsakit',
            name='kode_lokasi',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
