# Generated by Django 3.2.8 on 2021-11-06 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('day', models.IntegerField(primary_key=True, serialize=False, verbose_name='Day number')),
            ],
            options={
                'ordering': ['day'],
            },
        ),
        migrations.CreateModel(
            name='Quarantine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='Username')),
                ('start_timestamp', models.DateTimeField(blank=True, help_text='Leave empty on creation', verbose_name='Start timestamp')),
            ],
        ),
        migrations.CreateModel(
            name='QuarantineDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.day', verbose_name='Day data')),
                ('quarantine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.quarantine', verbose_name='Quarantine instance')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Task title')),
                ('description', models.TextField(blank=True, verbose_name='Task description')),
            ],
        ),
        migrations.CreateModel(
            name='QuarantineTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(default=False, verbose_name='Task done')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.quarantineday', verbose_name='Quarantine task day instance')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.task', verbose_name='Task data')),
            ],
        ),
        migrations.AddField(
            model_name='day',
            name='tasks',
            field=models.ManyToManyField(to='checklist.Task', verbose_name='Tasks for the day'),
        ),
    ]
