# Generated by Django 3.2.7 on 2021-10-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penyakit', models.CharField(max_length=30)),
                ('penjelasan', models.CharField(max_length=100)),
                ('daftar_obat', models.CharField(max_length=100)),
            ],
        ),
    ]
