# Generated by Django 3.2.7 on 2021-10-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obat',
            name='daftar_obat',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='obat',
            name='penjelasan',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='obat',
            name='penyakit',
            field=models.CharField(max_length=100),
        ),
    ]
