# Generated by Django 3.2.7 on 2021-10-24 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deteksi_mandiri', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='skor',
            new_name='result_score',
        ),
        migrations.AddField(
            model_name='answer',
            name='score',
            field=models.IntegerField(default=0, help_text='Score for each answer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='required_score_to_pass',
            field=models.IntegerField(help_text='Required score to be diagnosed negative in percent'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='time',
            field=models.IntegerField(help_text='Durations of the test in minutes'),
        ),
    ]
