# Generated by Django 3.2.9 on 2021-11-04 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deteksi_mandiri', '0002_auto_20211026_1431'),
        ('deteksi_mandiri', '0002_auto_20211027_1711'),
    ]

    operations = [
    ]
