# Generated by Django 3.2.7 on 2021-10-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deteksi_mandiri', '0003_auto_20211024_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='poin',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='required_score_to_pass',
            field=models.IntegerField(help_text='required score to diagnosed negative in per'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='time',
            field=models.IntegerField(help_text='durations of the quiz in minutes'),
        ),
    ]
