# Generated by Django 3.2.9 on 2021-11-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deteksi_mandiri', '0003_merge_0002_auto_20211026_1431_0002_auto_20211027_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='required_score_to_pass',
            field=models.IntegerField(help_text='required score to diagnosed negative in percent'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='time',
            field=models.IntegerField(help_text='durations of the quiz in minutes'),
        ),
    ]
