# Generated by Django 3.2.7 on 2021-10-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deteksi_mandiri', '0004_auto_20211026_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='required_score_to_pass',
            field=models.IntegerField(help_text='required score to diagnosed negative in percent'),
        ),
    ]
